<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Terminals Table
     *
     * A Terminal is a pre-registered Point of Sale unit belonging to a merchant.
     * It is the POS identity layer — the terminal_code is what identifies
     * a checkout device at payment time, not the merchant_code.
     *
     * Why terminals instead of merchant codes at POS:
     *   - A merchant can have multiple physical tills (Westlands branch,
     *     CBD branch, online checkout) — each gets its own terminal
     *   - Each terminal has a secret for request signing — if one terminal
     *     is compromised, only that terminal is revoked, not the whole merchant
     *   - Transaction records capture which specific till processed a payment,
     *     enabling per-terminal sales reports and fraud detection
     *
     * Onboarding flow:
     *   1. Merchant admin creates a terminal via the dashboard
     *   2. System generates terminal_code + terminal_secret
     *   3. terminal_secret is shown ONCE and then stored hashed
     *   4. The POS device is configured with these credentials
     *   5. At checkout: POS submits terminal_code + nialink_code + amount
     *
     * Operational check:
     *   A terminal is only operational if BOTH the terminal status = active
     *   AND the parent merchant status = active. Suspending a merchant
     *   instantly disables all their terminals without touching terminal rows.
     *
     * Foreign key dependency:
     *   terminals.merchant_id → merchants.id
     *   Merchants table must exist before this migration runs.
     */
    public function up(): void
    {
        Schema::create('terminals', function (Blueprint $table) {
            $table->uuid('id')->primary();

            // The merchant this terminal belongs to.
            // cascadeOnDelete: if a merchant is hard-deleted (rare, given softDeletes),
            // their terminals are removed too.
            $table->foreignUuid('merchant_id')
                ->constrained()
                ->cascadeOnDelete();

            // ── Identity ──

            // Human-readable name set by the merchant admin.
            // Shown in the dashboard and on transaction receipts.
            // Examples: "Main Till", "Westlands Branch", "Online Checkout"
            $table->string('name')
                ->comment('Human-readable label e.g. Main Till, Westlands Branch');

            // The public identifier submitted by the POS device at checkout.
            // Pre-configured on the device during onboarding — never typed manually.
            // Format: TRM-XXXXXXXX (generated by TerminalService on creation)
            $table->string('terminal_code')->unique()
                ->comment('Public POS identifier — pre-configured on the device');

            // Hashed secret used to sign payment requests from this terminal.
            // Verified server-side on every transaction claim.
            // Shown ONCE in plaintext at creation — never retrievable after that.
            $table->string('terminal_secret')
                ->comment('Bcrypt-hashed signing secret — shown once at creation');

            // ── Location & Context ──

            // Optional note to help the merchant admin identify the physical
            // location of this terminal in their dashboard.
            // Examples: "Ground floor", "Drive-through", "Nairobi CBD"
            $table->string('location_note')->nullable()
                ->comment('Optional physical location description for admin reference');

            // ── Status ──

            // active  → operational, can process payments
            // locked  → individually suspended (e.g. suspicious activity on one till)
            // inactive → decommissioned by merchant admin
            //
            // Note: a terminal with status = active is still non-operational
            // if its parent merchant status != active.
            // Always check Terminal::isOperational() not just this column.
            $table->enum('status', ['active', 'locked', 'inactive'])
                ->default('active')
                ->index();

            // ── Activity Tracking ──

            // Updated every time this terminal successfully processes a payment.
            // Used to detect dormant terminals and flag unusual activity patterns.
            $table->timestamp('last_active_at')->nullable()
                ->comment('Updated on every successful payment — used for activity monitoring');

            $table->timestamps();

            // Index for fast lookup of all terminals belonging to a merchant.
            // Used in the merchant dashboard and admin terminal list.
            $table->index('merchant_id');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('terminals');
    }
};
