<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Transactions Table
     *
     * The immutable header record for every financial event on NiaLink.
     *
     * What a transaction is NOT:
     *   It is not the money movement itself — that lives in ledger_entries.
     *   It is the authorisation record: who, what, when, how much, why.
     *
     * What a transaction IS:
     *   The parent record that one or two LedgerEntry rows hang off.
     *   A completed p2m payment creates exactly two ledger entries:
     *     - debit  → consumer wallet (full amount)
     *     - credit → merchant wallet (amount minus fee)
     *   The fee stays in the NiaLink float (the gap between debit and credit).
     *
     * Lifecycle by type:
     *   p2m (Nia-Code payment):
     *     pending → processing → completed | failed | expired
     *
     *   p2p (consumer transfer):
     *     pending → completed | failed
     *
     *   withdrawal:
     *     pending → completed | failed
     *
     *   topup:
     *     pending → completed | failed
     *     (created by ProcessMpesaTopUpCallback job, not directly)
     *
     * The nialink_code is NEVER stored here:
     *   The 6-digit code lives only in Redis with a 120-second TTL.
     *   payment_code_reference stores the Redis key name for audit purposes
     *   only — it cannot be used to replay or re-validate a payment.
     *
     * Foreign key dependency chain:
     *   transactions.user_id    → users.id
     *   transactions.merchant_id → merchants.id
     *   transactions.terminal_id → terminals.id
     *   transactions.sender_id  → users.id
     *   transactions.receiver_id → users.id
     *   All parent tables must exist before this migration runs.
     */
    public function up(): void
    {
        Schema::create('transactions', function (Blueprint $table) {
            $table->uuid('id')->primary();

            // ── Parties ──

            // The consumer who initiated this transaction.
            // For p2m: the customer paying.
            // For p2p: the sender.
            // For topup/withdrawal: the account holder.
            // Nullable: system-initiated transactions have no user actor.
            $table->foreignUuid('user_id')
                ->nullable()
                ->constrained()
                ->nullOnDelete();

            // For p2p transfers — explicit sender reference.
            // Same value as user_id for p2p, null for p2m/topup/withdrawal.
            $table->foreignUuid('sender_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete()
                ->comment('P2P sender — same as user_id for transfers');

            // For p2p transfers — the recipient.
            // Null for p2m payments and topup/withdrawal.
            $table->foreignUuid('receiver_id')
                ->nullable()
                ->constrained('users')
                ->nullOnDelete()
                ->comment('P2P recipient — null for p2m, topup, withdrawal');

            // The merchant receiving payment (p2m only).
            // Null for p2p transfers and topup/withdrawal.
            $table->foreignUuid('merchant_id')
                ->nullable()
                ->constrained()
                ->nullOnDelete();

            // The specific POS terminal that submitted the payment claim.
            // Null for p2p transfers and topup/withdrawal.
            // Enables per-terminal sales reporting and fraud detection.
            $table->foreignUuid('terminal_id')
                ->nullable()
                ->constrained()
                ->nullOnDelete()
                ->comment('The POS unit that processed this payment');

            // ── Reference ──

            // Public-facing unique reference shown on receipts and in support.
            // Format: NL-XXXXXXXX (generated by TransactionService)
            $table->string('reference')->unique()
                ->comment('Public receipt reference — format: NL-XXXXXXXX');

            // The Redis key that authorised this p2m transaction.
            // Stored for audit trail ONLY — cannot be used to replay payment.
            // The actual 6-digit code is never stored anywhere in the database.
            $table->string('payment_code_reference')->nullable()
                ->comment('Redis key reference for audit — not the code itself');

            // ── Financials ──

            $table->decimal('amount', 15, 2)->default(0.00)
                ->comment('Gross amount charged to the consumer');

            // NiaLink platform fee — currently 1% of amount.
            // The gap between what the consumer pays and what the merchant
            // receives. Stays in the NiaLink float account.
            $table->decimal('fee', 15, 2)->default(0.00)
                ->comment('NiaLink 1% platform fee — stays in float');

            $table->string('currency', 3)->default('KES');

            // ── Type & Status ──

            // p2m        → consumer pays merchant via Nia-Code
            // p2p        → consumer sends money to another consumer
            // withdrawal → consumer moves wallet balance to M-Pesa
            // topup      → M-Pesa funds enter the NiaLink wallet
            $table->enum('type', ['p2m', 'p2p', 'withdrawal', 'topup'])
                ->index();

            // pending    → code generated, no merchant claim yet (p2m)
            //              OR initiated but not yet settled (p2p/topup/withdrawal)
            // processing → merchant has claimed the code, waiting for settlement
            //              (p2m only — the window between claim and ledger write)
            // completed  → ledger entries written, money moved
            // failed     → something went wrong — no money moved
            // expired    → 120-second window passed without merchant claim
            $table->enum('status', ['pending', 'processing', 'completed', 'failed', 'expired'])
                ->default('pending')
                ->index();

            // Populated when status = failed — shown to consumer and logged.
            $table->string('failure_reason')->nullable();

            // ── Optional Context ──

            $table->string('description')->nullable()
                ->comment('Optional note — e.g. bill split description');

            // Flexible metadata for extended context without schema changes.
            // Examples: bill split shares, M-Pesa receipt number,
            //           merchant name at time of payment (denormalised for receipts)
            $table->json('metadata')->nullable()
                ->comment('Extended context — M-Pesa receipt, split shares, etc.');

            $table->timestamps();

            // ── Indexes ──

            // Most common query patterns:
            $table->index(['user_id', 'status']);           // Consumer transaction history
            $table->index(['merchant_id', 'status']);       // Merchant transaction history
            $table->index(['terminal_id', 'created_at']);   // Per-terminal reports
            $table->index(['type', 'status']);              // Admin ledger filtering
            $table->index('created_at');                    // Date range queries
        });

        // Partial index — fast lookup for the payment claim flow.
        // "Find the pending transaction for this Redis key" is the
        // hottest query in the system — happens on every payment claim.
        DB::statement("
            CREATE INDEX transactions_pending_code_lookup
            ON transactions (payment_code_reference)
            WHERE status = 'pending'
        ");
    }

    public function down(): void
    {
        DB::statement('DROP INDEX IF EXISTS transactions_pending_code_lookup');
        Schema::dropIfExists('transactions');
    }
};
