<?php

namespace App\Services;

use App\Models\User;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UserAuthService
{
    public function __construct(
        protected DeviceService $deviceService,
        protected OtpService    $otpService,
    ) {}

    /**
     * Create a new consumer user and their pending device row.
     * Both are created atomically — if either fails, both roll back.
     * Returns the user. OTP is generated by the controller after this.
     */
    public function registerConsumer(array $data): User
    {
        return DB::transaction(function () use ($data) {

            $user = User::create([
                'name'         => $data['name'],
                'phone_number' => $data['phone_number'],
                'pin'          => $data['pin'],         // cast: 'hashed' auto-bcrypts
                'primary_type' => 'consumer',
                'status'       => 'pending_verification',
                'kyc_level'    => 'tier_1',
                'currency'     => 'KES',
            ]);

            // Assign Spatie role — source of truth for permissions
            $user->assignRole('consumer');

            // Create the device row in pending state.
            // It becomes active when the user verifies their OTP.
            $user->devices()->create([
                'device_id'   => $data['device_id'],
                'fcm_token'   => $data['fcm_token']   ?? null,
                'device_name' => $data['device_name'] ?? null,
                'platform'    => $data['platform'],
                'app_version' => $data['app_version'] ?? null,
                'status'      => 'pending',
                'is_trusted'  => false,
            ]);

            return $user;
        });
    }

    /**
     * Verify the registration OTP.
     * On success: activates the user, trusts the device, issues a Sanctum token.
     * This is the single call that completes both phone verification
     * and device binding simultaneously.
     */
    public function verifyRegistrationOtp(User $user, string $otp, string $deviceId): array
    {
        // OtpService handles expiry and attempt limiting internally
        if (! $this->otpService->verify($user->phone_number, $otp)) {
            throw new \Exception('Invalid or expired OTP.', 401);
        }

        return DB::transaction(function () use ($user, $deviceId) {

            // Activate the user account
            $user->update(['status' => 'active']);

            // Trust the device — DeviceService handles displacing any
            // previous user on this device atomically
            $this->deviceService->trustDevice($user, $deviceId);

            // Issue Sanctum token — consumer is now fully onboarded
            $token = $user->createToken('mobile', ['consumer'])->plainTextToken;

            return [
                'token' => $token,
                'user'  => $user->fresh()->only(
                    'id', 'name', 'phone_number', 'kyc_level', 'currency'
                ),
            ];
        });
    }

    /**
     * Authenticate a consumer via phone number + PIN + device.
     * Returns a Sanctum token on success.
     * Throws on any failure — controller catches and returns the right HTTP code.
     */
    public function loginConsumer(string $phoneNumber, string $pin, string $deviceId): array
    {
        $user = User::where('phone_number', $phoneNumber)
            ->where('primary_type', 'consumer')
            ->first();

        // Use Hash::check() — never compare PINs with ===
        if (! $user || ! Hash::check($pin, $user->pin)) {
            throw new \Exception('Invalid phone number or PIN.', 401);
        }

        if ($user->status !== 'active') {
            throw new \Exception('Account is ' . $user->status . '.', 403);
        }

        if (! $this->deviceService->isActiveDevice($user, $deviceId)) {
            throw new \Exception('Unrecognised device.', 403);
        }

        $user->update(['last_login_at' => now()]);

        $token = $user->createToken('mobile', ['consumer'])->plainTextToken;

        return [
            'token' => $token,
            'user'  => $user->only('id', 'name', 'phone_number', 'kyc_level', 'currency'),
        ];
    }

    /**
     * Authenticate a merchant admin or staff member via email + password.
     * Returns a Sanctum token on success.
     */
    public function loginAdmin(string $email, string $password): array
    {
        $user = User::where('email', $email)
            ->whereIn('primary_type', ['merchant_admin', 'staff'])
            ->first();

        if (! $user || ! Hash::check($password, $user->password)) {
            throw new \Exception('Invalid email or password.', 401);
        }

        if ($user->status !== 'active') {
            throw new \Exception('Account is ' . $user->status . '.', 403);
        }

        $user->update(['last_login_at' => now()]);

        // Token ability scoped to their role
        $ability = $user->primary_type === 'merchant_admin'
            ? 'merchant_admin'
            : 'staff';

        $token = $user->createToken('web', [$ability])->plainTextToken;

        return [
            'token' => $token,
            'user'  => $user->only('id', 'name', 'email', 'primary_type'),
        ];
    }
}
